options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the news collector service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/news-collector', '-f', 'news-collector/Dockerfile', '.']

  # Push the news collector image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/news-collector']

  # Deploy news collector to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'briefly-news-collector'
      - '--image'
      - 'gcr.io/$PROJECT_ID/news-collector'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'EVENT_REGISTRY_API_KEY=${_EVENT_REGISTRY_API_KEY},DATABASE_URL=${_DATABASE_URL}'
      - '--port'
      - '8080'

images:
  - 'gcr.io/$PROJECT_ID/news-collector' 