steps:
  # Copy simple files to main locations
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        cp telegram-bot/simple_bot.py telegram-bot/bot.py
        cp telegram-bot/simple_dockerfile telegram-bot/Dockerfile  
        cp telegram-bot/simple_requirements.txt telegram-bot/requirements.txt

  # Build and deploy simple Telegram bot
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/telegram-bot-simple', './telegram-bot']
  - name: 'gcr.io/cloud-builders/docker'  
    args: ['push', 'gcr.io/$PROJECT_ID/telegram-bot-simple']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'telegram-bot-simple',
      '--image', 'gcr.io/$PROJECT_ID/telegram-bot-simple',
      '--region', 'europe-west1',
      '--platform', 'managed',
      '--no-allow-unauthenticated',
      '--set-env-vars', 'DATABASE_URL=$$DATABASE_URL,TELEGRAM_BOT_TOKEN=$$TELEGRAM_BOT_TOKEN',
      '--memory', '512Mi',
      '--cpu', '1000m',
      '--timeout', '3600',
      '--concurrency', '1',
      '--max-instances', '1'
    ]
    secretEnv: ['DATABASE_URL', 'TELEGRAM_BOT_TOKEN']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: 'DATABASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/TELEGRAM_BOT_TOKEN/versions/latest
      env: 'TELEGRAM_BOT_TOKEN' 